package com.carlettos.newwalls;

import java.util.LinkedList;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemGroups;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.registry.RegistryKey;
import net.minecraft.util.Identifier;
import net.minecraft.util.Pair;

public class NewItems {
    private static final LinkedList<Pair<Item, Identifier>> ITEMS = new LinkedList<>();
    
    public static final Logger LOGGER = LoggerFactory.getLogger("item_creation");
    
    public static final BlockItem QUARTZ_BLOCK_WALL = fromBlock(NewBlocks.QUARTZ_BLOCK_WALL, Blocks.QUARTZ_SLAB);
    public static final BlockItem PURPUR_BLOCK_WALL = fromBlock(NewBlocks.PURPUR_BLOCK_WALL, Blocks.PURPUR_SLAB);
    public static final BlockItem PRISMARINE_BRICK_WALL = fromBlock(NewBlocks.PRISMARINE_BRICK_WALL, Blocks.PRISMARINE_WALL);
    public static final BlockItem DARK_PRISMARINE_WALL = fromBlock(NewBlocks.DARK_PRISMARINE_WALL, Blocks.DARK_PRISMARINE_SLAB);
    public static final BlockItem SMOOTH_SANDSTONE_WALL = fromBlock(NewBlocks.SMOOTH_SANDSTONE_WALL, Blocks.SMOOTH_SANDSTONE_SLAB);
    public static final BlockItem SMOOTH_RED_SANDSTONE_WALL = fromBlock(NewBlocks.SMOOTH_RED_SANDSTONE_WALL, Blocks.SMOOTH_RED_SANDSTONE_SLAB);
    public static final BlockItem SMOOTH_QUARTZ_WALL = fromBlock(NewBlocks.SMOOTH_QUARTZ_WALL, Blocks.SMOOTH_QUARTZ_SLAB);
    public static final BlockItem STONE_WALL = fromBlock(NewBlocks.STONE_WALL, Blocks.STONE_SLAB);
    public static final BlockItem POLISHED_GRANITE_WALL = fromBlock(NewBlocks.POLISHED_GRANITE_WALL, Blocks.POLISHED_GRANITE_SLAB);
    public static final BlockItem POLISHED_DIORITE_WALL = fromBlock(NewBlocks.POLISHED_DIORITE_WALL, Blocks.POLISHED_DIORITE_SLAB);
    public static final BlockItem POLISHED_ANDESITE_WALL = fromBlock(NewBlocks.POLISHED_ANDESITE_WALL, Blocks.POLISHED_ANDESITE_SLAB);
    public static final BlockItem SMOOTH_STONE_STAIRS = fromBlock(NewBlocks.SMOOTH_STONE_STAIRS, Blocks.SMOOTH_STONE);
    public static final BlockItem SMOOTH_STONE_WALL = fromBlock(NewBlocks.SMOOTH_STONE_WALL, NewBlocks.SMOOTH_STONE_STAIRS);
    public static final BlockItem CUT_SANDSTONE_STAIRS = fromBlock(NewBlocks.CUT_SANDSTONE_STAIRS, Blocks.CUT_SANDSTONE_SLAB);
    public static final BlockItem CUT_SANDSTONE_WALL = fromBlock(NewBlocks.CUT_SANDSTONE_WALL, NewBlocks.CUT_SANDSTONE_STAIRS);
    public static final BlockItem CUT_RED_SANDSTONE_STAIRS = fromBlock(NewBlocks.CUT_RED_SANDSTONE_STAIRS, Blocks.CUT_RED_SANDSTONE_SLAB);
    public static final BlockItem CUT_RED_SANDSTONE_WALL = fromBlock(NewBlocks.CUT_RED_SANDSTONE_WALL, NewBlocks.CUT_RED_SANDSTONE_STAIRS);
    public static final BlockItem CRACKED_STONE_BRICK_STAIRS = fromBlock(NewBlocks.CRACKED_STONE_BRICK_STAIRS, Blocks.CHISELED_STONE_BRICKS);
    public static final BlockItem CRACKED_STONE_BRICK_SLAB = fromBlock(NewBlocks.CRACKED_STONE_BRICK_SLAB, NewBlocks.CRACKED_STONE_BRICK_STAIRS);
    public static final BlockItem CRACKED_STONE_BRICK_WALL = fromBlock(NewBlocks.CRACKED_STONE_BRICK_WALL, NewBlocks.CRACKED_STONE_BRICK_SLAB);
    public static final BlockItem CRACKED_NETHER_BRICK_STAIRS = fromBlock(NewBlocks.CRACKED_NETHER_BRICK_STAIRS, Blocks.CRACKED_NETHER_BRICKS);
    public static final BlockItem CRACKED_NETHER_BRICK_SLAB = fromBlock(NewBlocks.CRACKED_NETHER_BRICK_SLAB, NewBlocks.CRACKED_NETHER_BRICK_STAIRS);
    public static final BlockItem CRACKED_NETHER_BRICK_WALL = fromBlock(NewBlocks.CRACKED_NETHER_BRICK_WALL, NewBlocks.CRACKED_NETHER_BRICK_SLAB);
    public static final BlockItem CRACKED_NETHER_BRICK_FENCE = fromBlock(NewBlocks.CRACKED_NETHER_BRICK_FENCE, NewBlocks.CRACKED_NETHER_BRICK_WALL);
    public static final BlockItem CRACKED_NETHER_BRICK_FENCE_GATE = fromBlock(NewBlocks.CRACKED_NETHER_BRICK_FENCE_GATE, NewBlocks.CRACKED_NETHER_BRICK_FENCE);
    public static final BlockItem NETHER_BRICK_FENCE_GATE = fromBlock(NewBlocks.NETHER_BRICK_FENCE_GATE, Blocks.NETHER_BRICK_FENCE);
    public static final BlockItem RED_NETHER_BRICK_FENCE = fromBlock(NewBlocks.RED_NETHER_BRICK_FENCE, Blocks.RED_NETHER_BRICK_WALL);
    public static final BlockItem RED_NETHER_BRICK_FENCE_GATE = fromBlock(NewBlocks.RED_NETHER_BRICK_FENCE_GATE, NewBlocks.RED_NETHER_BRICK_FENCE);
    public static final BlockItem CRACKED_POLISHED_BLACKSTONE_BRICK_STAIRS = fromBlock(NewBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_STAIRS, Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS);
    public static final BlockItem CRACKED_POLISHED_BLACKSTONE_BRICK_SLAB = fromBlock(NewBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_SLAB, NewBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_STAIRS);
    public static final BlockItem CRACKED_POLISHED_BLACKSTONE_BRICK_WALL = fromBlock(NewBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_WALL, NewBlocks.CRACKED_POLISHED_BLACKSTONE_BRICK_SLAB);
    public static final BlockItem QUARTZ_BRICK_STAIRS = fromBlock(NewBlocks.QUARTZ_BRICK_STAIRS, Blocks.QUARTZ_BRICKS);
    public static final BlockItem QUARTZ_BRICK_SLAB = fromBlock(NewBlocks.QUARTZ_BRICK_SLAB, NewBlocks.QUARTZ_BRICK_STAIRS);
    public static final BlockItem QUARTZ_BRICK_WALL = fromBlock(NewBlocks.QUARTZ_BRICK_WALL, NewBlocks.QUARTZ_BRICK_SLAB);
    public static final BlockItem QUARTZ_BRICK_FENCE = fromBlock(NewBlocks.QUARTZ_BRICK_FENCE, NewBlocks.QUARTZ_BRICK_WALL);
    public static final BlockItem QUARTZ_BRICK_FENCE_GATE = fromBlock(NewBlocks.QUARTZ_BRICK_FENCE_GATE, NewBlocks.QUARTZ_BRICK_FENCE);
    public static final BlockItem CRACKED_DEEPSLATE_BRICK_STAIRS = fromBlock(NewBlocks.CRACKED_DEEPSLATE_BRICK_STAIRS, Blocks.CRACKED_DEEPSLATE_BRICKS);
    public static final BlockItem CRACKED_DEEPSLATE_BRICK_SLAB = fromBlock(NewBlocks.CRACKED_DEEPSLATE_BRICK_SLAB, NewBlocks.CRACKED_DEEPSLATE_BRICK_STAIRS);
    public static final BlockItem CRACKED_DEEPSLATE_BRICK_WALL = fromBlock(NewBlocks.CRACKED_DEEPSLATE_BRICK_WALL, NewBlocks.CRACKED_DEEPSLATE_BRICK_SLAB);
    public static final BlockItem CRACKED_DEEPSLATE_TILE_STAIRS = fromBlock(NewBlocks.CRACKED_DEEPSLATE_TILE_STAIRS, Blocks.CRACKED_DEEPSLATE_TILES);
    public static final BlockItem CRACKED_DEEPSLATE_TILE_SLAB = fromBlock(NewBlocks.CRACKED_DEEPSLATE_TILE_SLAB, NewBlocks.CRACKED_DEEPSLATE_TILE_STAIRS);
    public static final BlockItem CRACKED_DEEPSLATE_TILE_WALL = fromBlock(NewBlocks.CRACKED_DEEPSLATE_TILE_WALL, NewBlocks.CRACKED_DEEPSLATE_TILE_SLAB);
    public static final BlockItem TUFF_STAIRS = fromBlock(NewBlocks.TUFF_STAIRS, Blocks.TUFF, ItemGroups.NATURAL);
    public static final BlockItem TUFF_SLAB = fromBlock(NewBlocks.TUFF_SLAB, NewBlocks.TUFF_STAIRS, ItemGroups.NATURAL);
    public static final BlockItem TUFF_WALL = fromBlock(NewBlocks.TUFF_WALL, NewBlocks.TUFF_SLAB, ItemGroups.NATURAL);
    public static final BlockItem CALCITE_STAIRS = fromBlock(NewBlocks.CALCITE_STAIRS, Blocks.CALCITE, ItemGroups.NATURAL);
    public static final BlockItem CALCITE_SLAB = fromBlock(NewBlocks.CALCITE_SLAB, NewBlocks.CALCITE_STAIRS, ItemGroups.NATURAL);
    public static final BlockItem CALCITE_WALL = fromBlock(NewBlocks.CALCITE_WALL, NewBlocks.CALCITE_SLAB, ItemGroups.NATURAL);
    public static final BlockItem SMOOTH_BASALT_STAIRS = fromBlock(NewBlocks.SMOOTH_BASALT_STAIRS, Blocks.SMOOTH_BASALT, ItemGroups.NATURAL);
    public static final BlockItem SMOOTH_BASALT_SLAB = fromBlock(NewBlocks.SMOOTH_BASALT_SLAB, NewBlocks.SMOOTH_BASALT_STAIRS, ItemGroups.NATURAL);
    public static final BlockItem SMOOTH_BASALT_WALL = fromBlock(NewBlocks.SMOOTH_BASALT_WALL, NewBlocks.SMOOTH_BASALT_SLAB, ItemGroups.NATURAL);
    public static final BlockItem SCULK_STAIRS = fromBlock(NewBlocks.SCULK_STAIRS, Blocks.SCULK, ItemGroups.NATURAL);
    public static final BlockItem SCULK_SLAB = fromBlock(NewBlocks.SCULK_SLAB, NewBlocks.SCULK_STAIRS, ItemGroups.NATURAL);
    public static final BlockItem SCULK_WALL = fromBlock(NewBlocks.SCULK_WALL, NewBlocks.SCULK_SLAB, ItemGroups.NATURAL);
    public static final BlockItem SCULK_FENCE = fromBlock(NewBlocks.SCULK_FENCE, NewBlocks.SCULK_WALL, ItemGroups.NATURAL);
    public static final BlockItem SCULK_FENCE_GATE = fromBlock(NewBlocks.SCULK_FENCE_GATE, NewBlocks.SCULK_FENCE, ItemGroups.NATURAL);
    public static final BlockItem DRIPSTONE_BLOCK_STAIRS = fromBlock(NewBlocks.DRIPSTONE_BLOCK_STAIRS, Blocks.DRIPSTONE_BLOCK, ItemGroups.NATURAL);
    public static final BlockItem DRIPSTONE_BLOCK_SLAB = fromBlock(NewBlocks.DRIPSTONE_BLOCK_SLAB, NewBlocks.DRIPSTONE_BLOCK_STAIRS, ItemGroups.NATURAL);
    public static final BlockItem DRIPSTONE_BLOCK_WALL = fromBlock(NewBlocks.DRIPSTONE_BLOCK_WALL, NewBlocks.DRIPSTONE_BLOCK_SLAB, ItemGroups.NATURAL);
    public static final BlockItem COAL_BLOCK_STAIRS = fromBlock(NewBlocks.COAL_BLOCK_STAIRS, Blocks.COAL_BLOCK);
    public static final BlockItem COAL_BLOCK_SLAB = fromBlock(NewBlocks.COAL_BLOCK_SLAB, NewBlocks.COAL_BLOCK_STAIRS);
    public static final BlockItem COAL_BLOCK_WALL = fromBlock(NewBlocks.COAL_BLOCK_WALL, NewBlocks.COAL_BLOCK_SLAB);
    public static final BlockItem COAL_BLOCK_FENCE = fromBlock(NewBlocks.COAL_BLOCK_FENCE, NewBlocks.COAL_BLOCK_WALL);
    public static final BlockItem COAL_BLOCK_FENCE_GATE = fromBlock(NewBlocks.COAL_BLOCK_FENCE_GATE, NewBlocks.COAL_BLOCK_FENCE);
    public static final BlockItem CHISELED_SANDSTONE_STAIRS = fromBlock(NewBlocks.CHISELED_SANDSTONE_STAIRS, Blocks.CHISELED_SANDSTONE);
    public static final BlockItem CHISELED_SANDSTONE_SLAB = fromBlock(NewBlocks.CHISELED_SANDSTONE_SLAB, NewBlocks.CHISELED_SANDSTONE_STAIRS);
    public static final BlockItem CHISELED_SANDSTONE_WALL = fromBlock(NewBlocks.CHISELED_SANDSTONE_WALL, NewBlocks.CHISELED_SANDSTONE_STAIRS);
    public static final BlockItem WHITE_WOOL_STAIRS = fromBlock(NewBlocks.WHITE_WOOL_STAIRS, Blocks.WHITE_WOOL, ItemGroups.COLORED_BLOCKS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem WHITE_WOOL_SLAB = fromBlock(NewBlocks.WHITE_WOOL_SLAB, NewBlocks.WHITE_WOOL_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem WHITE_WOOL_WALL = fromBlock(NewBlocks.WHITE_WOOL_WALL, NewBlocks.WHITE_WOOL_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem ORANGE_WOOL_STAIRS = fromBlock(NewBlocks.ORANGE_WOOL_STAIRS, Blocks.ORANGE_WOOL, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem ORANGE_WOOL_SLAB = fromBlock(NewBlocks.ORANGE_WOOL_SLAB, NewBlocks.ORANGE_WOOL_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem ORANGE_WOOL_WALL = fromBlock(NewBlocks.ORANGE_WOOL_WALL, NewBlocks.ORANGE_WOOL_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem MAGENTA_WOOL_STAIRS = fromBlock(NewBlocks.MAGENTA_WOOL_STAIRS, Blocks.MAGENTA_WOOL, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem MAGENTA_WOOL_SLAB = fromBlock(NewBlocks.MAGENTA_WOOL_SLAB, NewBlocks.MAGENTA_WOOL_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem MAGENTA_WOOL_WALL = fromBlock(NewBlocks.MAGENTA_WOOL_WALL, NewBlocks.MAGENTA_WOOL_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIGHT_BLUE_WOOL_STAIRS = fromBlock(NewBlocks.LIGHT_BLUE_WOOL_STAIRS, Blocks.LIGHT_BLUE_WOOL, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIGHT_BLUE_WOOL_SLAB = fromBlock(NewBlocks.LIGHT_BLUE_WOOL_SLAB, NewBlocks.LIGHT_BLUE_WOOL_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIGHT_BLUE_WOOL_WALL = fromBlock(NewBlocks.LIGHT_BLUE_WOOL_WALL, NewBlocks.LIGHT_BLUE_WOOL_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem YELLOW_WOOL_STAIRS = fromBlock(NewBlocks.YELLOW_WOOL_STAIRS, Blocks.YELLOW_WOOL, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem YELLOW_WOOL_SLAB = fromBlock(NewBlocks.YELLOW_WOOL_SLAB, NewBlocks.YELLOW_WOOL_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem YELLOW_WOOL_WALL = fromBlock(NewBlocks.YELLOW_WOOL_WALL, NewBlocks.YELLOW_WOOL_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIME_WOOL_STAIRS = fromBlock(NewBlocks.LIME_WOOL_STAIRS, Blocks.LIME_WOOL, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIME_WOOL_SLAB = fromBlock(NewBlocks.LIME_WOOL_SLAB, NewBlocks.LIME_WOOL_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIME_WOOL_WALL = fromBlock(NewBlocks.LIME_WOOL_WALL, NewBlocks.LIME_WOOL_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem PINK_WOOL_STAIRS = fromBlock(NewBlocks.PINK_WOOL_STAIRS, Blocks.PINK_WOOL, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem PINK_WOOL_SLAB = fromBlock(NewBlocks.PINK_WOOL_SLAB, NewBlocks.PINK_WOOL_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem PINK_WOOL_WALL = fromBlock(NewBlocks.PINK_WOOL_WALL, NewBlocks.PINK_WOOL_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem GRAY_WOOL_STAIRS = fromBlock(NewBlocks.GRAY_WOOL_STAIRS, Blocks.GRAY_WOOL, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem GRAY_WOOL_SLAB = fromBlock(NewBlocks.GRAY_WOOL_SLAB, NewBlocks.GRAY_WOOL_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem GRAY_WOOL_WALL = fromBlock(NewBlocks.GRAY_WOOL_WALL, NewBlocks.GRAY_WOOL_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIGHT_GRAY_WOOL_STAIRS = fromBlock(NewBlocks.LIGHT_GRAY_WOOL_STAIRS, Blocks.LIGHT_GRAY_WOOL, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIGHT_GRAY_WOOL_SLAB = fromBlock(NewBlocks.LIGHT_GRAY_WOOL_SLAB, NewBlocks.LIGHT_GRAY_WOOL_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIGHT_GRAY_WOOL_WALL = fromBlock(NewBlocks.LIGHT_GRAY_WOOL_WALL, NewBlocks.LIGHT_GRAY_WOOL_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem CYAN_WOOL_STAIRS = fromBlock(NewBlocks.CYAN_WOOL_STAIRS, Blocks.CYAN_WOOL, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem CYAN_WOOL_SLAB = fromBlock(NewBlocks.CYAN_WOOL_SLAB, NewBlocks.CYAN_WOOL_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem CYAN_WOOL_WALL = fromBlock(NewBlocks.CYAN_WOOL_WALL, NewBlocks.CYAN_WOOL_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem PURPLE_WOOL_STAIRS = fromBlock(NewBlocks.PURPLE_WOOL_STAIRS, Blocks.PURPLE_WOOL, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem PURPLE_WOOL_SLAB = fromBlock(NewBlocks.PURPLE_WOOL_SLAB, NewBlocks.PURPLE_WOOL_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem PURPLE_WOOL_WALL = fromBlock(NewBlocks.PURPLE_WOOL_WALL, NewBlocks.PURPLE_WOOL_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BLUE_WOOL_STAIRS = fromBlock(NewBlocks.BLUE_WOOL_STAIRS, Blocks.BLUE_WOOL, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BLUE_WOOL_SLAB = fromBlock(NewBlocks.BLUE_WOOL_SLAB, NewBlocks.BLUE_WOOL_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BLUE_WOOL_WALL = fromBlock(NewBlocks.BLUE_WOOL_WALL, NewBlocks.BLUE_WOOL_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BROWN_WOOL_STAIRS = fromBlock(NewBlocks.BROWN_WOOL_STAIRS, Blocks.BROWN_WOOL, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BROWN_WOOL_SLAB = fromBlock(NewBlocks.BROWN_WOOL_SLAB, NewBlocks.BROWN_WOOL_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BROWN_WOOL_WALL = fromBlock(NewBlocks.BROWN_WOOL_WALL, NewBlocks.BROWN_WOOL_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem GREEN_WOOL_STAIRS = fromBlock(NewBlocks.GREEN_WOOL_STAIRS, Blocks.GREEN_WOOL, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem GREEN_WOOL_SLAB = fromBlock(NewBlocks.GREEN_WOOL_SLAB, NewBlocks.GREEN_WOOL_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem GREEN_WOOL_WALL = fromBlock(NewBlocks.GREEN_WOOL_WALL, NewBlocks.GREEN_WOOL_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem RED_WOOL_STAIRS = fromBlock(NewBlocks.RED_WOOL_STAIRS, Blocks.RED_WOOL, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem RED_WOOL_SLAB = fromBlock(NewBlocks.RED_WOOL_SLAB, NewBlocks.RED_WOOL_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem RED_WOOL_WALL = fromBlock(NewBlocks.RED_WOOL_WALL, NewBlocks.RED_WOOL_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BLACK_WOOL_STAIRS = fromBlock(NewBlocks.BLACK_WOOL_STAIRS, Blocks.BLACK_WOOL, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BLACK_WOOL_SLAB = fromBlock(NewBlocks.BLACK_WOOL_SLAB, NewBlocks.BLACK_WOOL_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BLACK_WOOL_WALL = fromBlock(NewBlocks.BLACK_WOOL_WALL, NewBlocks.BLACK_WOOL_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem OBSIDIAN_STAIRS = fromBlock(NewBlocks.OBSIDIAN_STAIRS, Blocks.OBSIDIAN, ItemGroups.NATURAL);
    public static final BlockItem OBSIDIAN_SLAB = fromBlock(NewBlocks.OBSIDIAN_SLAB, NewBlocks.OBSIDIAN_STAIRS, ItemGroups.NATURAL);
    public static final BlockItem OBSIDIAN_WALL = fromBlock(NewBlocks.OBSIDIAN_WALL, NewBlocks.OBSIDIAN_SLAB, ItemGroups.NATURAL);
    public static final BlockItem OBSIDIAN_FENCE = fromBlock(NewBlocks.OBSIDIAN_FENCE, NewBlocks.OBSIDIAN_WALL, ItemGroups.NATURAL);
    public static final BlockItem OBSIDIAN_FENCE_GATE = fromBlock(NewBlocks.OBSIDIAN_FENCE_GATE, NewBlocks.OBSIDIAN_FENCE, ItemGroups.NATURAL);
    public static final BlockItem SNOW_BLOCK_STAIRS = fromBlock(NewBlocks.SNOW_BLOCK_STAIRS, Blocks.SNOW_BLOCK, ItemGroups.NATURAL);
    public static final BlockItem SNOW_BLOCK_SLAB = fromBlock(NewBlocks.SNOW_BLOCK_SLAB, NewBlocks.SNOW_BLOCK_STAIRS, ItemGroups.NATURAL);
    public static final BlockItem SNOW_BLOCK_WALL = fromBlock(NewBlocks.SNOW_BLOCK_WALL, NewBlocks.SNOW_BLOCK_SLAB, ItemGroups.NATURAL);
    public static final BlockItem SNOW_BLOCK_FENCE = fromBlock(NewBlocks.SNOW_BLOCK_FENCE, NewBlocks.SNOW_BLOCK_WALL, ItemGroups.NATURAL);
    public static final BlockItem SNOW_BLOCK_FENCE_GATE = fromBlock(NewBlocks.SNOW_BLOCK_FENCE_GATE, NewBlocks.SNOW_BLOCK_FENCE, ItemGroups.NATURAL);
    public static final BlockItem CHISELED_STONE_BRICK_STAIRS = fromBlock(NewBlocks.CHISELED_STONE_BRICK_STAIRS, Blocks.CHISELED_STONE_BRICKS);
    public static final BlockItem CHISELED_STONE_BRICK_SLAB = fromBlock(NewBlocks.CHISELED_STONE_BRICK_SLAB, NewBlocks.CHISELED_STONE_BRICK_STAIRS);
    public static final BlockItem CHISELED_STONE_BRICK_WALL = fromBlock(NewBlocks.CHISELED_STONE_BRICK_WALL, NewBlocks.CHISELED_STONE_BRICK_SLAB);
    public static final BlockItem PACKED_MUD_STAIRS = fromBlock(NewBlocks.PACKED_MUD_STAIRS, Blocks.PACKED_MUD);
    public static final BlockItem PACKED_MUD_SLAB = fromBlock(NewBlocks.PACKED_MUD_SLAB, NewBlocks.PACKED_MUD_STAIRS);
    public static final BlockItem PACKED_MUD_WALL = fromBlock(NewBlocks.PACKED_MUD_WALL, NewBlocks.PACKED_MUD_SLAB);
    public static final BlockItem CHISELED_DEEPSLATE_STAIRS = fromBlock(NewBlocks.CHISELED_DEEPSLATE_STAIRS, Blocks.CHISELED_DEEPSLATE);
    public static final BlockItem CHISELED_DEEPSLATE_SLAB = fromBlock(NewBlocks.CHISELED_DEEPSLATE_SLAB, NewBlocks.CHISELED_DEEPSLATE_STAIRS);
    public static final BlockItem CHISELED_DEEPSLATE_WALL = fromBlock(NewBlocks.CHISELED_DEEPSLATE_WALL, NewBlocks.CHISELED_DEEPSLATE_SLAB);
    public static final BlockItem CHISELED_NETHER_BRICK_STAIRS = fromBlock(NewBlocks.CHISELED_NETHER_BRICK_STAIRS, Blocks.CHISELED_NETHER_BRICKS);
    public static final BlockItem CHISELED_NETHER_BRICK_SLAB = fromBlock(NewBlocks.CHISELED_NETHER_BRICK_SLAB, NewBlocks.CHISELED_NETHER_BRICK_STAIRS);
    public static final BlockItem CHISELED_NETHER_BRICK_WALL = fromBlock(NewBlocks.CHISELED_NETHER_BRICK_WALL, NewBlocks.CHISELED_NETHER_BRICK_SLAB);
    public static final BlockItem CHISELED_NETHER_BRICK_FENCE = fromBlock(NewBlocks.CHISELED_NETHER_BRICK_FENCE, NewBlocks.CHISELED_NETHER_BRICK_WALL);
    public static final BlockItem CHISELED_NETHER_BRICK_FENCE_GATE = fromBlock(NewBlocks.CHISELED_NETHER_BRICK_FENCE_GATE, NewBlocks.CHISELED_NETHER_BRICK_FENCE);
    public static final BlockItem CHISELED_QUARTZ_BLOCK_STAIRS = fromBlock(NewBlocks.CHISELED_QUARTZ_BLOCK_STAIRS, Blocks.CHISELED_QUARTZ_BLOCK);
    public static final BlockItem CHISELED_QUARTZ_BLOCK_SLAB = fromBlock(NewBlocks.CHISELED_QUARTZ_BLOCK_SLAB, NewBlocks.CHISELED_QUARTZ_BLOCK_STAIRS);
    public static final BlockItem CHISELED_QUARTZ_BLOCK_WALL = fromBlock(NewBlocks.CHISELED_QUARTZ_BLOCK_WALL, NewBlocks.CHISELED_QUARTZ_BLOCK_SLAB);
    public static final BlockItem CHISELED_QUARTZ_BLOCK_FENCE = fromBlock(NewBlocks.CHISELED_QUARTZ_BLOCK_FENCE, NewBlocks.CHISELED_QUARTZ_BLOCK_WALL);
    public static final BlockItem CHISELED_QUARTZ_BLOCK_FENCE_GATE = fromBlock(NewBlocks.CHISELED_QUARTZ_BLOCK_FENCE_GATE, NewBlocks.CHISELED_QUARTZ_BLOCK_FENCE);
    public static final BlockItem QUARTZ_BLOCK_FENCE = fromBlock(NewBlocks.QUARTZ_BLOCK_FENCE, Blocks.QUARTZ_BLOCK);
    public static final BlockItem QUARTZ_BLOCK_FENCE_GATE = fromBlock(NewBlocks.QUARTZ_BLOCK_FENCE_GATE, NewBlocks.QUARTZ_BLOCK_FENCE);
    public static final BlockItem WHITE_TERRACOTTA_STAIRS = fromBlock(NewBlocks.WHITE_TERRACOTTA_STAIRS, Blocks.WHITE_TERRACOTTA, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem WHITE_TERRACOTTA_SLAB = fromBlock(NewBlocks.WHITE_TERRACOTTA_SLAB, NewBlocks.WHITE_TERRACOTTA_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem WHITE_TERRACOTTA_WALL = fromBlock(NewBlocks.WHITE_TERRACOTTA_WALL, NewBlocks.WHITE_TERRACOTTA_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem ORANGE_TERRACOTTA_STAIRS = fromBlock(NewBlocks.ORANGE_TERRACOTTA_STAIRS, Blocks.ORANGE_TERRACOTTA, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem ORANGE_TERRACOTTA_SLAB = fromBlock(NewBlocks.ORANGE_TERRACOTTA_SLAB, NewBlocks.ORANGE_TERRACOTTA_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem ORANGE_TERRACOTTA_WALL = fromBlock(NewBlocks.ORANGE_TERRACOTTA_WALL, NewBlocks.ORANGE_TERRACOTTA_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem MAGENTA_TERRACOTTA_STAIRS = fromBlock(NewBlocks.MAGENTA_TERRACOTTA_STAIRS, Blocks.MAGENTA_TERRACOTTA, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem MAGENTA_TERRACOTTA_SLAB = fromBlock(NewBlocks.MAGENTA_TERRACOTTA_SLAB, NewBlocks.MAGENTA_TERRACOTTA_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem MAGENTA_TERRACOTTA_WALL = fromBlock(NewBlocks.MAGENTA_TERRACOTTA_WALL, NewBlocks.MAGENTA_TERRACOTTA_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIGHT_BLUE_TERRACOTTA_STAIRS = fromBlock(NewBlocks.LIGHT_BLUE_TERRACOTTA_STAIRS, Blocks.LIGHT_BLUE_TERRACOTTA, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIGHT_BLUE_TERRACOTTA_SLAB = fromBlock(NewBlocks.LIGHT_BLUE_TERRACOTTA_SLAB, NewBlocks.LIGHT_BLUE_TERRACOTTA_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIGHT_BLUE_TERRACOTTA_WALL = fromBlock(NewBlocks.LIGHT_BLUE_TERRACOTTA_WALL, NewBlocks.LIGHT_BLUE_TERRACOTTA_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem YELLOW_TERRACOTTA_STAIRS = fromBlock(NewBlocks.YELLOW_TERRACOTTA_STAIRS, Blocks.YELLOW_TERRACOTTA, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem YELLOW_TERRACOTTA_SLAB = fromBlock(NewBlocks.YELLOW_TERRACOTTA_SLAB, NewBlocks.YELLOW_TERRACOTTA_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem YELLOW_TERRACOTTA_WALL = fromBlock(NewBlocks.YELLOW_TERRACOTTA_WALL, NewBlocks.YELLOW_TERRACOTTA_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIME_TERRACOTTA_STAIRS = fromBlock(NewBlocks.LIME_TERRACOTTA_STAIRS, Blocks.LIME_TERRACOTTA, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIME_TERRACOTTA_SLAB = fromBlock(NewBlocks.LIME_TERRACOTTA_SLAB, NewBlocks.LIME_TERRACOTTA_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIME_TERRACOTTA_WALL = fromBlock(NewBlocks.LIME_TERRACOTTA_WALL, NewBlocks.LIME_TERRACOTTA_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem PINK_TERRACOTTA_STAIRS = fromBlock(NewBlocks.PINK_TERRACOTTA_STAIRS, Blocks.PINK_TERRACOTTA, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem PINK_TERRACOTTA_SLAB = fromBlock(NewBlocks.PINK_TERRACOTTA_SLAB, NewBlocks.PINK_TERRACOTTA_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem PINK_TERRACOTTA_WALL = fromBlock(NewBlocks.PINK_TERRACOTTA_WALL, NewBlocks.PINK_TERRACOTTA_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem GRAY_TERRACOTTA_STAIRS = fromBlock(NewBlocks.GRAY_TERRACOTTA_STAIRS, Blocks.GRAY_TERRACOTTA, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem GRAY_TERRACOTTA_SLAB = fromBlock(NewBlocks.GRAY_TERRACOTTA_SLAB, NewBlocks.GRAY_TERRACOTTA_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem GRAY_TERRACOTTA_WALL = fromBlock(NewBlocks.GRAY_TERRACOTTA_WALL, NewBlocks.GRAY_TERRACOTTA_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIGHT_GRAY_TERRACOTTA_STAIRS = fromBlock(NewBlocks.LIGHT_GRAY_TERRACOTTA_STAIRS, Blocks.LIGHT_GRAY_TERRACOTTA, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIGHT_GRAY_TERRACOTTA_SLAB = fromBlock(NewBlocks.LIGHT_GRAY_TERRACOTTA_SLAB, NewBlocks.LIGHT_GRAY_TERRACOTTA_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIGHT_GRAY_TERRACOTTA_WALL = fromBlock(NewBlocks.LIGHT_GRAY_TERRACOTTA_WALL, NewBlocks.LIGHT_GRAY_TERRACOTTA_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem CYAN_TERRACOTTA_STAIRS = fromBlock(NewBlocks.CYAN_TERRACOTTA_STAIRS, Blocks.CYAN_TERRACOTTA, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem CYAN_TERRACOTTA_SLAB = fromBlock(NewBlocks.CYAN_TERRACOTTA_SLAB, NewBlocks.CYAN_TERRACOTTA_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem CYAN_TERRACOTTA_WALL = fromBlock(NewBlocks.CYAN_TERRACOTTA_WALL, NewBlocks.CYAN_TERRACOTTA_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem PURPLE_TERRACOTTA_STAIRS = fromBlock(NewBlocks.PURPLE_TERRACOTTA_STAIRS, Blocks.PURPLE_TERRACOTTA, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem PURPLE_TERRACOTTA_SLAB = fromBlock(NewBlocks.PURPLE_TERRACOTTA_SLAB, NewBlocks.PURPLE_TERRACOTTA_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem PURPLE_TERRACOTTA_WALL = fromBlock(NewBlocks.PURPLE_TERRACOTTA_WALL, NewBlocks.PURPLE_TERRACOTTA_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BLUE_TERRACOTTA_STAIRS = fromBlock(NewBlocks.BLUE_TERRACOTTA_STAIRS, Blocks.BLUE_TERRACOTTA, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BLUE_TERRACOTTA_SLAB = fromBlock(NewBlocks.BLUE_TERRACOTTA_SLAB, NewBlocks.BLUE_TERRACOTTA_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BLUE_TERRACOTTA_WALL = fromBlock(NewBlocks.BLUE_TERRACOTTA_WALL, NewBlocks.BLUE_TERRACOTTA_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BROWN_TERRACOTTA_STAIRS = fromBlock(NewBlocks.BROWN_TERRACOTTA_STAIRS, Blocks.BROWN_TERRACOTTA, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BROWN_TERRACOTTA_SLAB = fromBlock(NewBlocks.BROWN_TERRACOTTA_SLAB, NewBlocks.BROWN_TERRACOTTA_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BROWN_TERRACOTTA_WALL = fromBlock(NewBlocks.BROWN_TERRACOTTA_WALL, NewBlocks.BROWN_TERRACOTTA_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem GREEN_TERRACOTTA_STAIRS = fromBlock(NewBlocks.GREEN_TERRACOTTA_STAIRS, Blocks.GREEN_TERRACOTTA, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem GREEN_TERRACOTTA_SLAB = fromBlock(NewBlocks.GREEN_TERRACOTTA_SLAB, NewBlocks.GREEN_TERRACOTTA_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem GREEN_TERRACOTTA_WALL = fromBlock(NewBlocks.GREEN_TERRACOTTA_WALL, NewBlocks.GREEN_TERRACOTTA_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem RED_TERRACOTTA_STAIRS = fromBlock(NewBlocks.RED_TERRACOTTA_STAIRS, Blocks.RED_TERRACOTTA, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem RED_TERRACOTTA_SLAB = fromBlock(NewBlocks.RED_TERRACOTTA_SLAB, NewBlocks.RED_TERRACOTTA_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem RED_TERRACOTTA_WALL = fromBlock(NewBlocks.RED_TERRACOTTA_WALL, NewBlocks.RED_TERRACOTTA_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BLACK_TERRACOTTA_STAIRS = fromBlock(NewBlocks.BLACK_TERRACOTTA_STAIRS, Blocks.BLACK_TERRACOTTA, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BLACK_TERRACOTTA_SLAB = fromBlock(NewBlocks.BLACK_TERRACOTTA_SLAB, NewBlocks.BLACK_TERRACOTTA_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BLACK_TERRACOTTA_WALL = fromBlock(NewBlocks.BLACK_TERRACOTTA_WALL, NewBlocks.BLACK_TERRACOTTA_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem CHISELED_RED_SANDSTONE_STAIRS = fromBlock(NewBlocks.CHISELED_RED_SANDSTONE_STAIRS, Blocks.CHISELED_RED_SANDSTONE);
    public static final BlockItem CHISELED_RED_SANDSTONE_SLAB = fromBlock(NewBlocks.CHISELED_RED_SANDSTONE_SLAB, NewBlocks.CHISELED_RED_SANDSTONE_STAIRS);
    public static final BlockItem CHISELED_RED_SANDSTONE_WALL = fromBlock(NewBlocks.CHISELED_RED_SANDSTONE_WALL, NewBlocks.CHISELED_RED_SANDSTONE_SLAB);
    public static final BlockItem NETHER_WART_BLOCK_STAIRS = fromBlock(NewBlocks.NETHER_WART_BLOCK_STAIRS, Blocks.NETHER_WART_BLOCK, ItemGroups.NATURAL);
    public static final BlockItem NETHER_WART_BLOCK_SLAB = fromBlock(NewBlocks.NETHER_WART_BLOCK_SLAB, NewBlocks.NETHER_WART_BLOCK_STAIRS, ItemGroups.NATURAL);
    public static final BlockItem NETHER_WART_BLOCK_WALL = fromBlock(NewBlocks.NETHER_WART_BLOCK_WALL, NewBlocks.NETHER_WART_BLOCK_SLAB, ItemGroups.NATURAL);
    public static final BlockItem WARPED_WART_BLOCK_STAIRS = fromBlock(NewBlocks.WARPED_WART_BLOCK_STAIRS, Blocks.WARPED_WART_BLOCK, ItemGroups.NATURAL);
    public static final BlockItem WARPED_WART_BLOCK_SLAB = fromBlock(NewBlocks.WARPED_WART_BLOCK_SLAB, NewBlocks.WARPED_WART_BLOCK_STAIRS, ItemGroups.NATURAL);
    public static final BlockItem WARPED_WART_BLOCK_WALL = fromBlock(NewBlocks.WARPED_WART_BLOCK_WALL, NewBlocks.WARPED_WART_BLOCK_SLAB, ItemGroups.NATURAL);
    public static final BlockItem CHISELED_POLISHED_BLACKSTONE_STAIRS = fromBlock(NewBlocks.CHISELED_POLISHED_BLACKSTONE_STAIRS, Blocks.CHISELED_POLISHED_BLACKSTONE);
    public static final BlockItem CHISELED_POLISHED_BLACKSTONE_SLAB = fromBlock(NewBlocks.CHISELED_POLISHED_BLACKSTONE_SLAB, NewBlocks.CHISELED_POLISHED_BLACKSTONE_STAIRS);
    public static final BlockItem CHISELED_POLISHED_BLACKSTONE_WALL = fromBlock(NewBlocks.CHISELED_POLISHED_BLACKSTONE_WALL, NewBlocks.CHISELED_POLISHED_BLACKSTONE_SLAB);
    public static final BlockItem CRYING_OBSIDIAN_STAIRS = fromBlock(NewBlocks.CRYING_OBSIDIAN_STAIRS, Blocks.CRYING_OBSIDIAN, ItemGroups.NATURAL);
    public static final BlockItem CRYING_OBSIDIAN_SLAB = fromBlock(NewBlocks.CRYING_OBSIDIAN_SLAB, NewBlocks.CRYING_OBSIDIAN_STAIRS, ItemGroups.NATURAL);
    public static final BlockItem CRYING_OBSIDIAN_WALL = fromBlock(NewBlocks.CRYING_OBSIDIAN_WALL, NewBlocks.CRYING_OBSIDIAN_SLAB, ItemGroups.NATURAL);
    public static final BlockItem CRYING_OBSIDIAN_FENCE = fromBlock(NewBlocks.CRYING_OBSIDIAN_FENCE, NewBlocks.CRYING_OBSIDIAN_WALL, ItemGroups.NATURAL);
    public static final BlockItem CRYING_OBSIDIAN_FENCE_GATE = fromBlock(NewBlocks.CRYING_OBSIDIAN_FENCE_GATE, NewBlocks.CRYING_OBSIDIAN_FENCE, ItemGroups.NATURAL);
    public static final BlockItem BLUE_ICE_STAIRS = fromBlock(NewBlocks.BLUE_ICE_STAIRS, Blocks.BLUE_ICE, ItemGroups.NATURAL);
    public static final BlockItem BLUE_ICE_SLAB = fromBlock(NewBlocks.BLUE_ICE_SLAB, NewBlocks.BLUE_ICE_STAIRS, ItemGroups.NATURAL);
    public static final BlockItem BLUE_ICE_WALL = fromBlock(NewBlocks.BLUE_ICE_WALL, NewBlocks.BLUE_ICE_SLAB, ItemGroups.NATURAL);
    public static final BlockItem BLUE_ICE_FENCE = fromBlock(NewBlocks.BLUE_ICE_FENCE, NewBlocks.BLUE_ICE_WALL, ItemGroups.NATURAL);
    public static final BlockItem BLUE_ICE_FENCE_GATE = fromBlock(NewBlocks.BLUE_ICE_FENCE_GATE, NewBlocks.BLUE_ICE_FENCE, ItemGroups.NATURAL);
    public static final BlockItem PACKED_ICE_STAIRS = fromBlock(NewBlocks.PACKED_ICE_STAIRS, Blocks.PACKED_ICE, ItemGroups.NATURAL);
    public static final BlockItem PACKED_ICE_SLAB = fromBlock(NewBlocks.PACKED_ICE_SLAB, NewBlocks.PACKED_ICE_STAIRS, ItemGroups.NATURAL);
    public static final BlockItem PACKED_ICE_WALL = fromBlock(NewBlocks.PACKED_ICE_WALL, NewBlocks.PACKED_ICE_SLAB, ItemGroups.NATURAL);
    public static final BlockItem PACKED_ICE_FENCE = fromBlock(NewBlocks.PACKED_ICE_FENCE, NewBlocks.PACKED_ICE_WALL, ItemGroups.NATURAL);
    public static final BlockItem PACKED_ICE_FENCE_GATE = fromBlock(NewBlocks.PACKED_ICE_FENCE_GATE, NewBlocks.PACKED_ICE_FENCE, ItemGroups.NATURAL);
    public static final BlockItem WHITE_CONCRETE_STAIRS = fromBlock(NewBlocks.WHITE_CONCRETE_STAIRS, Blocks.WHITE_CONCRETE, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem WHITE_CONCRETE_SLAB = fromBlock(NewBlocks.WHITE_CONCRETE_SLAB, NewBlocks.WHITE_CONCRETE_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem WHITE_CONCRETE_WALL = fromBlock(NewBlocks.WHITE_CONCRETE_WALL, NewBlocks.WHITE_CONCRETE_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem ORANGE_CONCRETE_STAIRS = fromBlock(NewBlocks.ORANGE_CONCRETE_STAIRS, Blocks.ORANGE_CONCRETE, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem ORANGE_CONCRETE_SLAB = fromBlock(NewBlocks.ORANGE_CONCRETE_SLAB, NewBlocks.ORANGE_CONCRETE_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem ORANGE_CONCRETE_WALL = fromBlock(NewBlocks.ORANGE_CONCRETE_WALL, NewBlocks.ORANGE_CONCRETE_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem MAGENTA_CONCRETE_STAIRS = fromBlock(NewBlocks.MAGENTA_CONCRETE_STAIRS, Blocks.MAGENTA_CONCRETE, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem MAGENTA_CONCRETE_SLAB = fromBlock(NewBlocks.MAGENTA_CONCRETE_SLAB, NewBlocks.MAGENTA_CONCRETE_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem MAGENTA_CONCRETE_WALL = fromBlock(NewBlocks.MAGENTA_CONCRETE_WALL, NewBlocks.MAGENTA_CONCRETE_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIGHT_BLUE_CONCRETE_STAIRS = fromBlock(NewBlocks.LIGHT_BLUE_CONCRETE_STAIRS, Blocks.LIGHT_BLUE_CONCRETE, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIGHT_BLUE_CONCRETE_SLAB = fromBlock(NewBlocks.LIGHT_BLUE_CONCRETE_SLAB, NewBlocks.LIGHT_BLUE_CONCRETE_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIGHT_BLUE_CONCRETE_WALL = fromBlock(NewBlocks.LIGHT_BLUE_CONCRETE_WALL, NewBlocks.LIGHT_BLUE_CONCRETE_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem YELLOW_CONCRETE_STAIRS = fromBlock(NewBlocks.YELLOW_CONCRETE_STAIRS, Blocks.YELLOW_CONCRETE, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem YELLOW_CONCRETE_SLAB = fromBlock(NewBlocks.YELLOW_CONCRETE_SLAB, NewBlocks.YELLOW_CONCRETE_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem YELLOW_CONCRETE_WALL = fromBlock(NewBlocks.YELLOW_CONCRETE_WALL, NewBlocks.YELLOW_CONCRETE_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIME_CONCRETE_STAIRS = fromBlock(NewBlocks.LIME_CONCRETE_STAIRS, Blocks.LIME_CONCRETE, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIME_CONCRETE_SLAB = fromBlock(NewBlocks.LIME_CONCRETE_SLAB, NewBlocks.LIME_CONCRETE_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIME_CONCRETE_WALL = fromBlock(NewBlocks.LIME_CONCRETE_WALL, NewBlocks.LIME_CONCRETE_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem PINK_CONCRETE_STAIRS = fromBlock(NewBlocks.PINK_CONCRETE_STAIRS, Blocks.PINK_CONCRETE, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem PINK_CONCRETE_SLAB = fromBlock(NewBlocks.PINK_CONCRETE_SLAB, NewBlocks.PINK_CONCRETE_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem PINK_CONCRETE_WALL = fromBlock(NewBlocks.PINK_CONCRETE_WALL, NewBlocks.PINK_CONCRETE_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem GRAY_CONCRETE_STAIRS = fromBlock(NewBlocks.GRAY_CONCRETE_STAIRS, Blocks.GRAY_CONCRETE, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem GRAY_CONCRETE_SLAB = fromBlock(NewBlocks.GRAY_CONCRETE_SLAB, NewBlocks.GRAY_CONCRETE_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem GRAY_CONCRETE_WALL = fromBlock(NewBlocks.GRAY_CONCRETE_WALL, NewBlocks.GRAY_CONCRETE_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIGHT_GRAY_CONCRETE_STAIRS = fromBlock(NewBlocks.LIGHT_GRAY_CONCRETE_STAIRS, Blocks.LIGHT_GRAY_CONCRETE, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIGHT_GRAY_CONCRETE_SLAB = fromBlock(NewBlocks.LIGHT_GRAY_CONCRETE_SLAB, NewBlocks.LIGHT_GRAY_CONCRETE_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem LIGHT_GRAY_CONCRETE_WALL = fromBlock(NewBlocks.LIGHT_GRAY_CONCRETE_WALL, NewBlocks.LIGHT_GRAY_CONCRETE_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem CYAN_CONCRETE_STAIRS = fromBlock(NewBlocks.CYAN_CONCRETE_STAIRS, Blocks.CYAN_CONCRETE, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem CYAN_CONCRETE_SLAB = fromBlock(NewBlocks.CYAN_CONCRETE_SLAB, NewBlocks.CYAN_CONCRETE_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem CYAN_CONCRETE_WALL = fromBlock(NewBlocks.CYAN_CONCRETE_WALL, NewBlocks.CYAN_CONCRETE_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem PURPLE_CONCRETE_STAIRS = fromBlock(NewBlocks.PURPLE_CONCRETE_STAIRS, Blocks.PURPLE_CONCRETE, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem PURPLE_CONCRETE_SLAB = fromBlock(NewBlocks.PURPLE_CONCRETE_SLAB, NewBlocks.PURPLE_CONCRETE_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem PURPLE_CONCRETE_WALL = fromBlock(NewBlocks.PURPLE_CONCRETE_WALL, NewBlocks.PURPLE_CONCRETE_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BLUE_CONCRETE_STAIRS = fromBlock(NewBlocks.BLUE_CONCRETE_STAIRS, Blocks.BLUE_CONCRETE, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BLUE_CONCRETE_SLAB = fromBlock(NewBlocks.BLUE_CONCRETE_SLAB, NewBlocks.BLUE_CONCRETE_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BLUE_CONCRETE_WALL = fromBlock(NewBlocks.BLUE_CONCRETE_WALL, NewBlocks.BLUE_CONCRETE_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BROWN_CONCRETE_STAIRS = fromBlock(NewBlocks.BROWN_CONCRETE_STAIRS, Blocks.BROWN_CONCRETE, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BROWN_CONCRETE_SLAB = fromBlock(NewBlocks.BROWN_CONCRETE_SLAB, NewBlocks.BROWN_CONCRETE_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BROWN_CONCRETE_WALL = fromBlock(NewBlocks.BROWN_CONCRETE_WALL, NewBlocks.BROWN_CONCRETE_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem GREEN_CONCRETE_STAIRS = fromBlock(NewBlocks.GREEN_CONCRETE_STAIRS, Blocks.GREEN_CONCRETE, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem GREEN_CONCRETE_SLAB = fromBlock(NewBlocks.GREEN_CONCRETE_SLAB, NewBlocks.GREEN_CONCRETE_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem GREEN_CONCRETE_WALL = fromBlock(NewBlocks.GREEN_CONCRETE_WALL, NewBlocks.GREEN_CONCRETE_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem RED_CONCRETE_STAIRS = fromBlock(NewBlocks.RED_CONCRETE_STAIRS, Blocks.RED_CONCRETE, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem RED_CONCRETE_SLAB = fromBlock(NewBlocks.RED_CONCRETE_SLAB, NewBlocks.RED_CONCRETE_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem RED_CONCRETE_WALL = fromBlock(NewBlocks.RED_CONCRETE_WALL, NewBlocks.RED_CONCRETE_SLAB, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BLACK_CONCRETE_STAIRS = fromBlock(NewBlocks.BLACK_CONCRETE_STAIRS, Blocks.BLACK_CONCRETE, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BLACK_CONCRETE_SLAB = fromBlock(NewBlocks.BLACK_CONCRETE_SLAB, NewBlocks.BLACK_CONCRETE_STAIRS, ItemGroups.COLORED_BLOCKS);
    public static final BlockItem BLACK_CONCRETE_WALL = fromBlock(NewBlocks.BLACK_CONCRETE_WALL, NewBlocks.BLACK_CONCRETE_SLAB, ItemGroups.COLORED_BLOCKS);

    public static final BlockItem fromBlock(Block block, Block nextTo) {
    	return fromBlock(block, nextTo, ItemGroups.BUILDING_BLOCKS);
    }
    
    @SafeVarargs
	public static final BlockItem fromBlock(Block block, Block nextTo, RegistryKey<ItemGroup>... groups) {
    	for (RegistryKey<ItemGroup> registryKey : groups) {
        	ItemGroupEvents.modifyEntriesEvent(registryKey).register(c -> c.addAfter(nextTo, block));
		}
        BlockItem item = new BlockItem(block, new FabricItemSettings());
        common(block, item);
        return item;
    }

    public static final void common(Block parent, Item item) {
        var registryKey = Registries.BLOCK.getKey(parent);
        
        Identifier blockName = null;
        if (registryKey.isPresent()) {
             blockName = registryKey.get().getValue();
        }
        
        if (blockName == null) {
            LOGGER.warn("Problem adding automatic name to: " + item + " parent doesn't exist on registry");
            return;
        }
        
        ITEMS.add(new Pair<>(item, blockName));
    }
    
    public static final void register() {
        ITEMS.forEach(pair -> Registry.register(Registries.ITEM, pair.getRight(), pair.getLeft()));
    }
}
